server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://120.77.32.252:3306/JavaEEManagement?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ZJ123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  # redis
  redis:
    host: 120.77.32.252
    database: 0
    port: 6379
    password: ZJ123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: 'notFe8PYzFmfi8wTcP_pjv9KxwB3CGdX1LOrj7Vv'
  secretKey: 'VafkdwQl_Gn5k1JhLhSBP0x2gc_e5Q1XU5uec2hn'
  bucket: 'zj-myblog'

